version: "3.2"
services:
  php:
    build: './php/'
    environment:
      DB_HOST: database
      DB_NAME: boxbilling
      DB_USER: root
      DB_PASS: root
    networks:
      - backend
    volumes:
      - ./html/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
networks:
  frontend:
  backend: